//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("_S_ServiceDescription_S_")]
[assembly: AssemblyCompany("_S_CompanyName_S_")]
[assembly: AssemblyProduct("_S_ServiceLibraryProjectName_S_")]
[assembly: AssemblyCopyright("Copyright © _S_CompanyName_S_ 2015")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.15348.3.")]
[assembly: AssemblyVersion("1.0.15348.3")]
[assembly: AssemblyFileVersion("1.0.15348.3")]


