//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _S_LibraryProjectName_S_.Service_References._S_ShortProductName_S_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="_S_ServiceProjectName_S_", ConfigurationName="_S_ShortProductName_S_Service.I_S_ShortProductName_S_Manager")]
    public interface I_S_ShortProductName_S_Manager {
        
        [System.ServiceModel.OperationContractAttribute(Action="_S_ServiceProjectName_S_/I_S_ShortProductName_S_Manager/SomeExampleServiceMethod", ReplyAction="_S_ServiceProjectName_S_/I_S_ShortProductName_S_Manager/SomeExampleServiceMethodR" +
            "esponse")]
        void SomeExampleServiceMethod(string someExampleparameter);
        
        [System.ServiceModel.OperationContractAttribute(Action="_S_ServiceProjectName_S_/I_S_ShortProductName_S_Manager/SomeExampleServiceMethod", ReplyAction="_S_ServiceProjectName_S_/I_S_ShortProductName_S_Manager/SomeExampleServiceMethodR" +
            "esponse")]
        System.Threading.Tasks.Task SomeExampleServiceMethodAsync(string someExampleparameter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_S_ShortProductName_S_ManagerChannel : I_S_ShortProductName_S_Manager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_S_ShortProductName_S_ManagerClient : System.ServiceModel.ClientBase<I_S_ShortProductName_S_Manager>, I_S_ShortProductName_S_Manager {
        
        public I_S_ShortProductName_S_ManagerClient() {
        }
        
        public I_S_ShortProductName_S_ManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_S_ShortProductName_S_ManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_S_ShortProductName_S_ManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_S_ShortProductName_S_ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SomeExampleServiceMethod(string someExampleparameter) {
            base.Channel.SomeExampleServiceMethod(someExampleparameter);
        }
        
        public System.Threading.Tasks.Task SomeExampleServiceMethodAsync(string someExampleparameter) {
            return base.Channel.SomeExampleServiceMethodAsync(someExampleparameter);
        }
    }
}
